
export const database = [
    {
        id:0,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:15,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:1,
        act:86,
        number:10386,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:2,
        act:86,
        number:10387,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:3,
        act:86,
        number:10388,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:4,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:5,
        act:86,
        number:1032,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:6,
        act:86,
        number:11485,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:7,
        act:86,
        number:135,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:8,
        act:86,
        number:5346,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:9,
        act:86,
        number:835,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:10,
        act:86,
        number:124677,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },{
        id:11,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:12,
        act:86,
        number:10386,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:13,
        act:86,
        number:10387,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:14,
        act:86,
        number:10388,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:15,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:16,
        act:86,
        number:1032,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:17,
        act:86,
        number:11485,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:18,
        act:86,
        number:135,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:19,
        act:86,
        number:5346,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:20,
        act:86,
        number:835,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:21,
        act:86,
        number:124677,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },{
        id:22,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:23,
        act:86,
        number:10386,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:24,
        act:86,
        number:10387,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:25,
        act:86,
        number:10388,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:26,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:27,
        act:86,
        number:1032,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:28,
        act:86,
        number:11485,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:29,
        act:86,
        number:135,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:30,
        act:86,
        number:5346,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:31,
        act:86,
        number:835,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:32,
        act:86,
        number:124677,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },{
        id:33,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:34,
        act:86,
        number:10386,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:35,
        act:86,
        number:10387,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:36,
        act:86,
        number:10388,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:37,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:38,
        act:86,
        number:1032,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:39,
        act:86,
        number:11485,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:40,
        act:86,
        number:135,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:41,
        act:86,
        number:5346,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:42,
        act:86,
        number:835,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:43,
        act:86,
        number:124677,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },{
        id:44,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:45,
        act:86,
        number:10386,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:46,
        act:86,
        number:10387,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:47,
        act:86,
        number:10388,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:48,
        act:86,
        number:10385,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:49,
        act:86,
        number:1032,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:50,
        act:86,
        number:11485,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:51,
        act:86,
        number:135,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:52,
        act:86,
        number:5346,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:53,
        act:86,
        number:835,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:11,
        scanDate:'',
        scaner:15,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },
    {
        id:54,
        act:86,
        number:124677,
        adress: 'some adress here',
        incomeDate: '10.08.20',
        outDate:'' ,
        jointDate:'',
        jointer:0,
        scanDate:'',
        scaner:0,
        pages:0,
        stitchDate:'',
        stitcher:0,
        choosen: false,
        visible: true,

    },

    ]